<template lang="html">
  <b-row>
    <b-col cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="access-point-url-group"
        label-cols="4"
        label="Access point:"
        label-for="access-point-url"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="access-point-url"
          ref="deviceAPUrl"
          v-model="accessPointUrl"
          type="url"
          size="sm"
          autocomplete="url"
          placeholder="will be used to generate a qr code"
          required
          @change="deviceAPUrl"
        />
      </b-form-group>
    </b-col>
    <b-col cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-eui-group"
        label-cols="4"
        label="Device EUI :"
        label-for="device-eui"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="device-eui"
          ref="deviceDevEui"
          v-model="devEui"
          type="text"
          size="sm"
          autocomplete="username"
          placeholder="generated by your device"
          required
          @change="deviceDevEui"
        />
      </b-form-group>
    </b-col>
  </b-row>
</template>

<script type="text/javascript">
import has from 'lodash.has';
import { BFormGroup, BFormInput } from 'bootstrap-vue';

export default {
  name: 'AloesClientForm',

  components: {
    'b-form-input': BFormInput,
    'b-form-group': BFormGroup,
  },

  props: {
    'is-viewer': {
      type: Boolean,
      default: true,
    },
    'edit-mode': {
      type: Boolean,
      default: true,
    },
  },

  data() {
    return {
      viewer: true,
      editorMode: false,
      complete: false,
      updatedStatus: null,
    };
  },

  computed: {
    success: {
      get() {
        return this.$store.state.device.success;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'success',
          value,
        });
      },
    },
    error: {
      get() {
        return this.$store.state.device.error;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'error',
          value,
        });
      },
    },
    dismissSecs: {
      get() {
        return this.$store.state.device.dismissSecs;
      },
    },
    dismissCountDown: {
      get() {
        return this.$store.state.device.dismissCountDown;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'dismissCountDown',
          value,
        });
      },
    },
    device: {
      get() {
        return this.$store.state.device.instance;
      },
      set(value) {
        this.$store.commit('device/setModel', value);
      },
    },
    deviceIdExists() {
      return has(this.device, 'id');
    },
    // specific device properties
    appEui: {
      get() {
        return this.$store.state.device.instance.appEui;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'appEui',
          value,
        });
      },
    },
    devEui: {
      get() {
        return this.$store.state.device.instance.devEui;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'devEui',
          value,
        });
      },
    },
    authMode: {
      get() {
        return this.$store.state.device.instance.authMode;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'authMode',
          value,
        });
      },
    },
    accessPointUrl: {
      get() {
        return this.$store.state.device.instance.accessPointUrl;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'accessPointUrl',
          value,
        });
      },
    },
    messageProtocol: {
      get() {
        return this.$store.state.device.instance.messageProtocol;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'messageProtocol',
          value,
        });
      },
    },
  },

  watch: {
    isViewer: {
      handler(state) {
        this.viewer = state;
      },
      immediate: true,
    },
    editMode: {
      handler(mode) {
        this.editorMode = mode;
      },
      immediate: true,
    },
    accessPointUrl() {
      this.updateDeviceForm();
    },
    devEui() {
      this.updateDeviceForm();
    },
    // devEui() {
    //   this.updateDeviceForm();
    // },
  },

  mounted() {
    this.messageProtocol = this.$store.state.device.instance.transportProtocol;
  },

  updated() {
    this.messageProtocol = this.$store.state.device.instance.transportProtocol;
  },

  beforeDestroy() {
    this.reset();
  },

  methods: {
    reset() {
      this.viewer = true;
      this.editorMode = false;
      this.complete = false;
      this.updatedStatus = null;
      this.updatedNwkSKey = null;
      this.updatedAppSKey = null;
      this.updatedAppKey = null;
    },

    deviceDevEui() {
      if (this.devEui !== null && this.devEui.length && this.devEui.length > 5) return true;
      return false;
    },

    deviceAPUrl() {
      if (
        this.accessPointUrl !== null &&
        this.accessPointUrl.length &&
        this.accessPointUrl.length > 2
      )
        return true;
      return false;
    },

    updateDeviceForm() {
      if (this.deviceIdExists) this.complete = true;
      else {
        this.complete = this.deviceAPUrl() && this.deviceDevEui();
      }
    },
  },
};
</script>

<style lang="scss" scoped>
@import '../../style/device-editor.scss';
</style>
