<template lang="html">
  <b-row>
    <b-col sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-message-protocol-group"
        label-cols="4"
        label="Message API :"
        label-for="device-message-protocol"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-select
          id="device-message-protocol"
          ref="deviceMessageProtocol"
          v-model="messageProtocol"
          :options="messageProtocolNames"
          size="sm"
          required
        />
      </b-form-group>
    </b-col>
    <b-col sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-auth-mode-group"
        label-cols="4"
        label="Auth mode :"
        label-for="device-auth-mode"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-select
          id="device-auth-mode"
          ref="deviceProtocolName"
          v-model="authMode"
          :options="loraWANAuthModes"
          size="sm"
          required
        />
      </b-form-group>
    </b-col>

    <b-col cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="app-eui-group"
        label-cols="4"
        label="App EUI :"
        label-for="app-eui"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="app-eui"
          ref="deviceAppEui"
          v-model="appEui"
          type="text"
          size="sm"
          autocomplete="off"
          placeholder="Lorawan Server Id"
          required
        />
      </b-form-group>
    </b-col>

    <b-col v-if="authMode === 'ABP'" cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-addr-group"
        label-cols="4"
        label="Device Address :"
        label-for="device-addr"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="device-addr"
          ref="deviceDevAddr"
          v-model="devAddr"
          type="text"
          size="sm"
          autocomplete="off"
          placeholder="generated by your device"
          required
        />
      </b-form-group>
    </b-col>
    <b-col v-if="authMode === 'ABP'" cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-appSKey-group"
        label-cols="4"
        label="AppSKey :"
        label-for="device-appSKey"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="device-appSKey"
          ref="deviceAppSKey"
          v-model="appSKey"
          type="text"
          size="sm"
          autocomplete="off"
          placeholder="click to autogenerate"
          required
          @click.native="generateAppSKey"
        />
      </b-form-group>
    </b-col>
    <b-col v-if="authMode === 'ABP'" cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-nwkSKey-group"
        label-cols="4"
        label="NwkSKey :"
        label-for="device-nwkSKey"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="device-nwkSKey"
          ref="deviceNwkSKey"
          v-model="nwkSKey"
          type="text"
          size="sm"
          autocomplete="off"
          placeholder="click to autogenerate"
          required
          @click.native="generateNwkSKey"
        />
      </b-form-group>
    </b-col>
    <b-col v-if="authMode === 'OTAA'" cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-eui-group"
        label-cols="4"
        label="Device EUI :"
        label-for="device-eui"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="device-eui"
          ref="deviceDevEui"
          v-model="devEui"
          type="text"
          size="sm"
          autocomplete="username"
          placeholder="generated by your device"
          required
          @change="deviceDevEui"
        />
      </b-form-group>
    </b-col>
    <b-col v-if="authMode === 'OTAA'" cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="join-eui-group"
        label-cols="4"
        label="Join EUI :"
        label-for="join-eui"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="join-eui"
          ref="deviceJoinEui"
          v-model="joinEui"
          type="text"
          size="sm"
          autocomplete="off"
          placeholder="generated by your device"
          required
        />
      </b-form-group>
    </b-col>
    <b-col v-if="authMode === 'OTAA'" cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-appKey-group"
        label-cols="4"
        label="AppKey :"
        label-for="device-appKey"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="device-appKey"
          ref="deviceAppKey"
          v-model="appKey"
          type="text"
          size="sm"
          autocomplete="off"
          placeholder="click to autogenerate"
          required
          @click.native="generateAppKey"
        />
      </b-form-group>
    </b-col>
  </b-row>
</template>

<script type="text/javascript">
import has from 'lodash.has';
import bFormInput from 'bootstrap-vue/es/components/form-input/form-input';
import bFormGroup from 'bootstrap-vue/es/components/form-group/form-group';
import bFormSelect from 'bootstrap-vue/es/components/form-select/form-select';
import builder from '@/services/builder';

export default {
  name: 'LoraWanForm',

  components: {
    'b-form-input': bFormInput,
    'b-form-group': bFormGroup,
    'b-form-select': bFormSelect,
  },

  props: {
    'is-viewer': {
      type: Boolean,
      default: true,
    },
    'edit-mode': {
      type: Boolean,
      default: true,
    },
  },

  data() {
    return {
      viewer: true,
      editorMode: false,
      complete: false,
      updatedStatus: null,
      updatedNwkSKey: null,
      updatedAppSKey: null,
      updatedAppKey: null,
      loraWANAuthModes: [
        { text: 'type', value: null, disabled: true },
        { text: 'ABP', value: 'ABP' },
        { text: 'OTAA', value: 'OTAA' },
      ],
      messageProtocolNames: [
        { text: 'name', value: null, disabled: true },
        { text: 'AloesLight', value: 'aloesLight' },
        { text: 'CayenneLPP', value: 'cayenneLPP' },
      ],
    };
  },

  computed: {
    success: {
      get() {
        return this.$store.state.device.success;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'success',
          value,
        });
      },
    },
    error: {
      get() {
        return this.$store.state.device.error;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'error',
          value,
        });
      },
    },
    dismissSecs: {
      get() {
        return this.$store.state.device.dismissSecs;
      },
    },
    dismissCountDown: {
      get() {
        return this.$store.state.device.dismissCountDown;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'dismissCountDown',
          value,
        });
      },
    },
    device: {
      get() {
        return this.$store.state.device.instance;
      },
      set(value) {
        this.$store.commit('device/setModel', value);
      },
    },
    deviceIdExists() {
      return has(this.device, 'id');
    },
    // specific device properties
    messageProtocol: {
      get() {
        return this.$store.state.device.instance.messageProtocol;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'messageProtocol',
          value,
        });
      },
    },
    appEui: {
      get() {
        return this.$store.state.device.instance.appEui;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'appEui',
          value,
        });
      },
    },
    devEui: {
      get() {
        return this.$store.state.device.instance.devEui;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'devEui',
          value,
        });
      },
    },
    devAddr: {
      get() {
        return this.$store.state.device.instance.devAddr;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'devAddr',
          value,
        });
      },
    },
    authMode: {
      get() {
        return this.$store.state.device.instance.authMode;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'authMode',
          value,
        });
      },
    },
    appKey: {
      get() {
        return this.$store.state.device.instance.appKey;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'appKey',
          value,
        });
      },
    },
    joinEui: {
      get() {
        return this.$store.state.device.instance.joinEui;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'joinEui',
          value,
        });
      },
    },
    appSKey: {
      get() {
        return this.$store.state.device.instance.appSKey;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'appSKey',
          value,
        });
      },
    },
    nwkSKey: {
      get() {
        return this.$store.state.device.instance.nwkSKey;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'nwkSKey',
          value,
        });
      },
    },
  },

  watch: {
    isViewer: {
      handler(state) {
        this.viewer = state;
      },
      immediate: true,
    },
    editMode: {
      handler(mode) {
        this.editorMode = mode;
      },
      immediate: true,
    },
    nwkSKey: {
      handler(key) {
        this.updatedNwkSKey = key;
      },
      immediate: true,
    },
    appSKey: {
      handler(key) {
        this.updatedAppSKey = key;
      },
      immediate: true,
    },
    appKey: {
      handler(key) {
        this.updatedAppKey = key;
      },
      immediate: true,
    },
    // devEui() {
    //   this.updateDeviceForm();
    // },
  },

  mounted() {
    //  this.reset();
  },

  beforeDestroy() {
    this.reset();
  },

  methods: {
    reset() {
      this.viewer = true;
      this.editorMode = false;
      this.complete = false;
      this.updatedStatus = null;
      this.updatedNwkSKey = null;
      this.updatedAppSKey = null;
      this.updatedAppKey = null;
    },

    deviceDevEui() {
      if (this.devEui !== null && this.devEui.length && this.devEui.length > 5) return true;
      return false;
    },

    updateDeviceForm() {
      if (this.deviceIdExists) this.complete = true;
      else {
        this.complete = this.deviceDevEui();
      }
    },

    async generateNwkSKey() {
      if (!this.nwkSKey || this.nwkSKey === null) {
        const key = await builder.generateKeys(32);
        this.nwkSKey = key;
        return key;
      }
      return null;
    },

    async generateAppSKey() {
      if (!this.appSKey || this.appSKey === null) {
        const key = await builder.generateKeys(32);
        this.appSKey = key;
        return key;
      }
      return null;
    },

    async generateAppKey() {
      if (!this.appKey || this.appKey === null) {
        const key = await builder.generateKeys(32);
        this.appKey = key;
        return key;
      }
      return null;
    },

    // async generateKeys(howMany, chars) {
    //   try {
    //     chars =
    //       chars ||
    //       'abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789';
    //     const rnd = await crypto.randomBytes(howMany);
    //     const value = new Array(howMany);
    //     const len = Math.min(256, chars.length);
    //     const d = 256 / len;
    //     for (let i = 0; i < howMany; i++) {
    //       value[i] = chars[Math.floor(rnd[i] / d)];
    //     }
    //     const key = value
    //       .join('')
    //       .toString()
    //       .toUpperCase();
    //     return key;
    //   } catch (error) {
    //     return error;
    //   }
    // },
  },
};
</script>

<style lang="scss" scoped>
@import '../../style/device-editor.scss';
</style>
