<template lang="html">
  <b-row>
    <b-col cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="access-point-url-group"
        label-cols="4"
        label="Access point:"
        label-for="access-point-url"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="access-point-url"
          ref="deviceAPUrl"
          v-model="accessPointUrl"
          type="url"
          size="sm"
          autocomplete="url"
          placeholder="will be used to generate a qr code"
          required
          @change="deviceAPUrl"
        />
      </b-form-group>
    </b-col>
    <b-col cols="12" sm="12" md="6" lg="6" xl="6">
      <b-form-group
        id="device-eui-group"
        label-cols="4"
        label="Device EUI :"
        label-for="device-eui"
        label-size="sm"
        breakpoint="sm"
      >
        <b-form-input
          id="device-eui"
          ref="deviceDevEui"
          v-model="devEui"
          type="text"
          size="sm"
          autocomplete="username"
          placeholder="generated by your device"
          required
          @change="deviceDevEui"
        />
      </b-form-group>
    </b-col>
  </b-row>
</template>

<script type="text/javascript">
import has from 'lodash.has';
import bFormInput from 'bootstrap-vue/es/components/form-input/form-input';
import bFormGroup from 'bootstrap-vue/es/components/form-group/form-group';

export default {
  name: 'MySensorsForm',

  components: {
    'b-form-input': bFormInput,
    'b-form-group': bFormGroup,
  },

  props: {
    'is-viewer': {
      type: Boolean,
      default: true,
    },
    'edit-mode': {
      type: Boolean,
      default: true,
    },
  },

  data() {
    return {
      viewer: true,
      editorMode: false,
      complete: false,
      updatedStatus: null,
    };
  },

  computed: {
    success: {
      get() {
        return this.$store.state.device.success;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'success',
          value,
        });
      },
    },
    error: {
      get() {
        return this.$store.state.device.error;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'error',
          value,
        });
      },
    },
    dismissSecs: {
      get() {
        return this.$store.state.device.dismissSecs;
      },
    },
    dismissCountDown: {
      get() {
        return this.$store.state.device.dismissCountDown;
      },
      set(value) {
        this.$store.commit('device/setStateKV', {
          key: 'dismissCountDown',
          value,
        });
      },
    },
    device: {
      get() {
        return this.$store.state.device.instance;
      },
      set(value) {
        this.$store.commit('device/setModel', value);
      },
    },
    deviceIdExists() {
      //  console.log(has(this.device, "id"));
      return has(this.device, 'id');
    },
    // specific device properties

    devEui: {
      get() {
        return this.$store.state.device.instance.devEui;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'devEui',
          value,
        });
      },
    },
    accessPointUrl: {
      get() {
        return this.$store.state.device.instance.accessPointUrl;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'accessPointUrl',
          value,
        });
      },
    },
    messageProtocol: {
      get() {
        return this.$store.state.device.instance.messageProtocol;
      },
      set(value) {
        this.$store.commit('device/setModelKV', {
          key: 'messageProtocol',
          value,
        });
      },
    },
  },

  watch: {
    isViewer: {
      handler(state) {
        this.viewer = state;
      },
      immediate: true,
    },
    editMode: {
      handler(mode) {
        this.editorMode = mode;
      },
      immediate: true,
    },
    accessPointUrl() {
      this.updateDeviceForm();
    },
    devEui() {
      this.updateDeviceForm();
    },
  },

  mounted() {
    //  console.log('profile form', this.status)
    this.messageProtocol = this.$store.state.device.instance.transportProtocol;
  },

  methods: {
    deviceDevEui() {
      if (this.devEui !== null && this.devEui.length && this.devEui.length > 5) return true;
      return false;
    },
    deviceAPUrl() {
      if (
        this.accessPointUrl !== null &&
        this.accessPointUrl.length &&
        this.accessPointUrl.length > 2
      )
        return true;
      return false;
    },

    updateDeviceForm() {
      if (this.deviceIdExists) this.complete = true;
      else {
        this.complete = this.deviceAPUrl() && this.deviceDevEui();
      }

      // if (this.deviceName()) {
      //   if (!this.deviceAPUrl()) {
      //     this.$refs.deviceAPUrl.focus();
      //   } else if (!this.deviceDevEui()) {
      //     this.$refs.deviceDevEui.focus();
      //   }
      //   //  else if (!this.deviceProtocol()) {
      //   //   this.$refs.deviceProtocol.focus();
      //   // }
      // } else if (this.deviceAPUrl()) {
      //   if (!this.deviceDevEui()) {
      //     this.$refs.deviceDevEui.focus();
      //   } else if (!this.deviceName()) {
      //     this.$refs.deviceName.focus();
      //   }
      //   //  else if (!this.deviceProtocol()) {
      //   //   this.$refs.deviceProtocol.focus();
      //   // }
      // } else if (this.deviceProtocol()) {
      //   if (!this.deviceDevEui()) {
      //     this.$refs.deviceDevEui.focus();
      //   } else if (!this.deviceName()) {
      //     this.$refs.deviceName.focus();
      //   } else if (!this.deviceAPUrl()) {
      //     this.$refs.cardExpiry.focus();
      //   }
      // }
    },
  },
};
</script>

<style lang="scss" scoped>
@import '../../style/device-editor.scss';
</style>
