# Copyright 2019 Edouard Maleix, read LICENSE

version: '3.7'

services:
  client:
    env_file: deploy/.env_docker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_NAME=ALOES
        - VUE_APP_DOMAIN=${VUE_APP_DOMAIN}
        - VUE_APP_SERVER_URL=${VUE_APP_SERVER_URL}
        - VUE_APP_BROKER_URL=${VUE_APP_BROKER_URL}
        - VUE_APP_ROOT_API=${VUE_APP_ROOT_API}
        - VUE_APP_CLIENT_URL=${VUE_APP_CLIENT_URL}
        - VUE_APP_LOGGER_LEVEL=${VUE_APP_LOGGER_LEVEL}
        - GIT_REPO_SSH_URL=git@framagit.org:aloes/aloes-client.git
    image: aloes/aloes-client:0.5
    volumes:
      - ./deploy/.env_docker:/home/node/aloes-client/.env:ro

  client-server:
    environment:
      - NGINX_HTTP_SERVER_PORT=${NGINX_HTTP_SERVER_PORT}
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    restart: always
    volumes:
      - ./config/nginx/nginx-local.template:/etc/nginx/nginx.template
    depends_on:
      - client
    ports:
      - '${NGINX_HTTP_SERVER_PORT}:${NGINX_HTTP_SERVER_PORT}'
    expose:
      - ${NGINX_HTTP_SERVER_PORT}
    command: /bin/bash -c "envsubst '$${NGINX_HTTP_SERVER_PORT}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
