# Copyright 2019 Edouard Maleix, read LICENSE

version: '3.7'

services:
  client:
    env_file: deploy/.env_docker
    build:
      context: .
      dockerfile: local.dockerfile
      args:
        - VUE_APP_NAME=ALOES
        - VUE_APP_DOMAIN=${VUE_APP_DOMAIN}
        - VUE_APP_SERVER_URL=${VUE_APP_SERVER_URL}
        - VUE_APP_BROKER_URL=${VUE_APP_BROKER_URL}
        - VUE_APP_ROOT_API=${VUE_APP_ROOT_API}
        - VUE_APP_CLIENT_URL=${VUE_APP_CLIENT_URL}
        - VUE_APP_LOGGER_LEVEL=${VUE_APP_LOGGER_LEVEL}
        - GIT_REPO_SSH_URL=git@framagit.org:aloes/aloes-client.git
    image: getlarge/aloes-client:0.5
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
      - '3000'
  