version: '3.7'

services:
  client:
    container_name: aloes-client
    hostname: aloes-client
    env_file: deploy/.env_docker
    build:
      context: .
      dockerfile: ${NODE_ENV}.dockerfile
      args:
        - VUE_APP_NAME=ALOES
        - VUE_APP_DOMAIN=localhost
        - VUE_APP_SERVER_URL=http://localhost:8000
        - VUE_APP_BROKER_URL=ws://ed-X510URR:8000
        - VUE_APP_ROOT_API=/api
        - VUE_APP_CLIENT_URL=http://localhost:8080
        - VUE_APP_LOGGER_LEVEL=3
        - GIT_REPO_SSH_URL=git@framagit.org:aloes/aloes-client.git
    image: getlarge/${NODE_NAME}:0.5
    restart: always
    ports:
      - '8080:80'
    expose:
      - '80'
      - '8000'
  